### ISSUE TITLE
Can't create new TODO

### ISSUE THREAD

**Issue by leobano** [libasys/tasksplus#18]
When I try to create a new task list , the button does nothing.

Error   PHP Call to a member function getAsString() on a non-object at /opt/www/owncloud/apps/tasksplus/lib/share/backend/vtodo.php#73  2015-09-19T04:03:31+00:00

Fatal   index   Exception: {"Exception":"Doctrine\DBAL\Exception\SyntaxErrorException","Message":"An exception occurred while executing 'SELECT \* FROM `oc_clndrplus_objects` WHERE `objecttype`= ? AND ( ) ORDER BY relatedto ASC, calendarid ASC, startdate DESC' with params [\"VTODO\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') ORDER BY relatedto ASC, calendarid ASC, startdate DESC' at line 1","Code":0,"Trace":"#0 \/opt\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))\n#1 \/opt\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Statement.php(172): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT \* FROM `...', Array)\n#2 \/opt\/www\/owncloud\/lib\/private\/db\/statementwrapper.php(73): Doctrine\DBAL\Statement->execute(Array)\n#3 \/opt\/www\/owncloud\/apps\/tasksplus\/lib\/app.php(311): OC_DB_StatementWrapper->execute(Array)\n#4 \/opt\/www\/owncloud\/apps\/tasksplus\/lib\/search\/provider.php(85): OCA\TasksPlus\App::all('')\n#5 \/opt\/www\/owncloud\/lib\/private\/search.php(69): OCA\TasksPlus\Search\Provider->search('rendici')\n#6 \/opt\/www\/owncloud\/core\/search\/ajax\/search.php(56): OC\Search->searchPaged('rendici', Array, 1, 30)\n#7 \/opt\/www\/owncloud\/lib\/private\/route\/route.php(154) : runtime-created function(1): require_once('\/opt\/www\/ownclo...')\n#8 [internal function]: __lambda_func(Array)\n#9 \/opt\/www\/owncloud\/lib\/private\/route\/router.php(274): call_user_func('?lambda_1544', Array)\n#10 \/opt\/www\/owncloud\/lib\/base.php(874): OC\Route\Router->match('\/core\/search')\n#11 \/opt\/www\/owncloud\/index.php(40): OC::handleRequest()\n#12 {main}","File":"\/opt\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","Line":90}

ownCloud 8.1.3
##

**Comment by riggs498** [comment]
This is not working for me either. Wondering if you figured out a fix yet?
